### ISSUE TITLE
support minimp3, lower CPU usage

### ISSUE THREAD

**Issue by anhoder** [anhoder/go-musicfox#16]
support [minimp3](https://github.com/tosone/minimp3)

**Comment by WXZhao7** [comment]
我来催更了😜

**Comment by anhoder** [comment]
musicfox现在正在研究MacOS下调用系统播放器的可能性，加上最近工作比较忙，所以这边版本更新会晚些

**Comment by anhoder** [comment]
[v3.0.1](https://github.com/anhoder/go-musicfox/releases/tag/v3.0.1)已实现
