### ISSUE TITLE
播放音乐时会卡住

### ISSUE THREAD

**Issue by amaomaoa** [anhoder/go-musicfox#2]
archlinux ;自己把源码下载下来编译的

**Comment by anhoder** [comment]
有必现的场景吗

**Comment by amaomaoa** [comment]
一台电脑一播放就卡住，另一台完全没问题，我晕，还是一样的系统

**Comment by anhoder** [comment]
😂这就很难处理了，可能跟电脑硬件驱动有关

**Comment by amaomaoa** [comment]
用musicfox不会，用musicbox时也是这样。。。

**Comment by anhoder** [comment]
你可以尝试编译之前，先更新一下faiface/beep依赖，go-musicfox是依赖这个包播放音频的。看最新版的faiface/beep有没有这个问题

**Comment by amaomaoa** [comment]
已经搞定了，是alsa的问题

**Comment by amaomaoa** [comment]
有没有考虑过后台播放，然后可以通过命令行查看当前歌词，这样子就可以用xsetroot实现状态栏歌词了

**Comment by anhoder** [comment]
暂时不会，身边没有linux设备
