### ISSUE TITLE
无法正常登录帐号

### ISSUE THREAD

**Issue by DHWIDSA** [anhoder/go-musicfox#20]
密码帐号均输入正确，但是提示密码错误

**Comment by anhoder** [comment]
网易云登录接口调整，v2.2.1 已修复

**Comment by suricatta** [comment]
我也还是登陆不上，Version:2.2.1

**Comment by DHWIDSA** [comment]
> 我也还是登陆不上，Version:2.2.1
Version:2.2.1
OS: Arch Linux
无法复现

**Comment by DHWIDSA** [comment]
> 我也还是登陆不上，Version:2.2.1



> 我也还是登陆不上，Version:2.2.1

Version:2.2.1
OS: Arch Linux
无法复现

**Comment by DHWIDSA** [comment]
> 我也还是登陆不上，Version:2.2.1

Version:2.2.1
OS: Arch Linux
无法复现

**Comment by anhoder** [comment]
Mac 2.2.1

**Comment by anhoder** [comment]
Mac下2.2.1也无法复现，可以正常登录

命令行输入`musicfox --version`或者`musicfox -h`看下版本对不对
