### ISSUE TITLE
请支持XDG Base Directory规范

### ISSUE THREAD

**Issue by phoon** [anhoder/go-musicfox#21]
希望遵循该规范:https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
目前.go-musicfox放置在家目录(污染), 可以这样拆分:
cookie -> $XDG_STATE_HOME/go-musixfox/cookie
music_cache -> $XDG_CACHE_HOME/go-musixfox/music-cache
logo.png -> $XDG_CONFIG_HOME/go-musicfox/logo.png
go-musicfox.ini -> $XDG_CONFIG_HOME/go-musicfox/go-musicfox.ini
db -> $XDG_DATA_HOME/go-musicfox/db

**Comment by phoon** [comment]
或者直接全放 $XDG_DATA_HOME/go-musicfox下(~/.local/share/go-musicfox)

**Comment by anhoder** [comment]
可以加个配置支持

**Comment by anhoder** [comment]
增加[环境变量`MUSICFOX_ROOT`](https://github.com/anhoder/go-musicfox/commit/bab4dd88d0c2da8652707b39819887c3fb369756) 用于配置主目录(*开发分支2.3.0，暂未发布*)
