### ISSUE TITLE
[Feature Request] Unblock Netease Music支持？

### ISSUE THREAD

**Issue by Riceneeder** [anhoder/go-musicfox#22]
请问大佬是否考虑内置[UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server)|[Rust版](https://github.com/UnblockNeteaseMusic/server-rust)
或者添加一个设置代理的选项
大佬的go-musicfox完全能日常使用，如果能解锁灰色和vip歌曲那就锦上添花了（XD

**Comment by anhoder** [comment]
研究下

**Comment by anhoder** [comment]
v3.1.0 接入了 https://github.com/cnsilvan/UnblockNeteaseMusic

效果：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/27605589/193503906-98246b21-fd42-4d7d-8a27-105843c7dfb8.png">

**Comment by Riceneeder** [comment]
好诶  芜湖！
