### ISSUE TITLE
[Feature Request] 记住上次使用时的音量

### ISSUE THREAD

**Issue by ston-afk** [anhoder/go-musicfox#24]
每次打开musicfox时音量总是需要调整，不然会过小或者过大，能否增加一个设置选项来支持这个功能，这样不需要每次调整音量，会方便很多

**Comment by anhoder** [comment]
musicfox的音量和系统音量现在是分开的，我觉得把musicfox的音量调到最大，然后只调节系统音量应该更方便点

**Comment by anhoder** [comment]
[v3.0.1](https://github.com/anhoder/go-musicfox/releases/tag/v3.0.1)已实现
