### ISSUE TITLE
Release源码编译的二进制打开时会提示有新版本可用

### ISSUE THREAD

**Issue by ston-afk** [anhoder/go-musicfox#29]
通过最新release版本的源码go build出来的musicfox在打开时会提示有新版本可用

**Comment by anhoder** [comment]
编译的时候需要注入版本

**Comment by ston-afk** [comment]
> 编译的时候需要注入版本，
> 
> ```shell
> go build -ldflags "-s -w -X go-musicfox/pkg/constants.AppVersion=v3.2.2" cmd/musicfox.go
> ```

好的，这样编译之后不会提示了
