### ISSUE TITLE
功能建议：集成 MPRIS

### ISSUE THREAD

**Issue by xzsk2** [anhoder/go-musicfox#30]
[MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) 在大多数发行版中都有良好的集成，可以通过菜单栏/控件等方式控制播放状态，使用上比较类似 [Mac NowPlaying](https://github.com/anhoder/go-musicfox#7-mac-nowplaying)

目前的 musicfox 想要使用 MPRIS 似乎只能配置 MPD 并安装 [mpd-mpris](https://github.com/natsukagami/mpd-mpris)，但因为 musicfox 另起了一个 MPD 进程，mpd-mpris 并没有生效。考虑到 MPD 为外部实现可能不太方便集成，能否在使用内置的 beep 引擎时实现 MPRIS 功能呢

**Comment by anhoder** [comment]
[v3.3.1](https://github.com/anhoder/go-musicfox/releases/tag/v3.3.1)已支持，只在ubuntu下进行了测试

**Comment by Aleksanaa** [comment]
> [v3.3.1](https://github.com/anhoder/go-musicfox/releases/tag/v3.3.1)已支持，只在ubuntu下进行了测试

Arch Linux latest 工作正常，谢谢大大
