### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by h304192** [anhoder/go-musicfox#32]
1、播放歌曲的时候，按`R`会导致界面显示错乱：
![image](https://user-images.githubusercontent.com/109783518/202844529-b1aa3ba5-ad65-481b-a6b5-5e8d2335cfd5.png)
2、按了多少下`C`就得按多少下`ESC`才能回到原来的界面

**Comment by anhoder** [comment]
1. cmd下的显示可能会有有问题（短时间内应该不会兼容），Windows下推荐使用Terminal
2. 这个问题下个版本会进行修复

**Comment by anhoder** [comment]
1. cmd的显示问题暂时不会处理（身边没有Windows机器）
2. [v3.3.3](https://github.com/anhoder/go-musicfox/releases/tag/v3.3.3) 已修复
