### ISSUE TITLE
建议在配置文件指定下载文件位置

### ISSUE THREAD

**Issue by sunwgit** [anhoder/go-musicfox#34]
现在只能下载到`~/.go-musicfox/download`, 而且下载完成后通知也没说明, 还找了半天, 原来在这里.
还是写道配置文件最好, 免得又要`mv`

**Comment by anhoder** [comment]
v3.5.0已增加配置
<img width="837" alt="image" src="https://user-images.githubusercontent.com/27605589/208235192-7a44a15d-f34b-4394-b77f-3fce81e1ea5e.png">
