### ISSUE TITLE
通知出错

### ISSUE THREAD

**Issue by TheCryingGame** [anhoder/go-musicfox#35]
当前版本：MacOS 10.15.7 (19H15)
<img width="327" alt="image" src="https://user-images.githubusercontent.com/48227194/204970289-1369aed9-88ec-473d-9474-acdd52a26ffb.png">

**Comment by anhoder** [comment]
正常的，Mac如果没有安装terminal-notifier就会使用osascript发送通知，效果就是这样的

**Comment by TheCryingGame** [comment]
老哥，我Mac NowPlaying的导航栏也没有不显示那个小标题

**Comment by TheCryingGame** [comment]
更新版本后还是无法自动切歌

**Comment by anhoder** [comment]
#25 加这个群，问题说详细一点

**Comment by anhoder** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/27605589/205440811-af09d61e-26fd-44db-9136-f40f9cf09f4a.png">
