### ISSUE TITLE
希望下载歌曲时自带歌曲封面和信息

### ISSUE THREAD

**Issue by flemon-y** [anhoder/go-musicfox#39]
虽然目前现在的版本支持歌曲下载功能,对于我这种需要下载歌曲到本地上来说非常方便,但是我下载过来的歌曲是不带歌曲封面和信息,导致我部分本地音乐播放器检测不到歌手和专辑是谁,而且没有封面显示也非常难受,希望下个版本支持音乐封面图和信息,省得自己手动添加.

**Comment by anhoder** [comment]
暂时没找到比较好的golang tags编辑包，后续再看看

**Comment by flemon-y** [comment]
行吧。

**Comment by anhoder** [comment]
[v3.6.0](https://github.com/anhoder/go-musicfox/releases/tag/v3.6.0)已支持
