### ISSUE TITLE
歌单里只能列出前一千首歌

### ISSUE THREAD

**Issue by xzsk2** [anhoder/go-musicfox#42]
包括《我喜欢的音乐》和其他歌单都受影响

比如这个歌单 https://music.163.com/#/playlist?id=139746382 只能显示前一千首

**Comment by anhoder** [comment]
已知问题，现在只会加载前一千首，我觉得超过一千全加载没什么太大意义，还浪费内存

**Comment by xzsk2** [comment]
或许可以加个选项由用户选择是否加载一千以后的歌曲？🤔

**Comment by anhoder** [comment]
[v3.6.0](https://github.com/anhoder/go-musicfox/releases/tag/v3.6.0)已发布，增加配置支持`showAllSongsOfPlaylist `
