### ISSUE TITLE
如果按一个键能看到某首歌（比如正在播放或者菜单中选中的）的所属歌手和所在的专辑就好了

### ISSUE THREAD

**Issue by duoduoffff** [anhoder/go-musicfox#49]
如题，这个要求应该不难吧

比如，按 i 键，显示这首歌所属的歌手名下的专辑列表，按 l 键，显示这首歌所在的专辑

这个 feature 一直没做进去，私以为这是很基础的功能

**Comment by anhoder** [comment]
v3.7.0已实现
