### ISSUE TITLE
歌曲放了几首后报错

### ISSUE THREAD

**Issue by jlduu** [anhoder/go-musicfox#5]
An existing connection was forcibly closed by the remote host.

**Comment by anhoder** [comment]
应该是网络原因，我这边没有出现

**Comment by canwushuang** [comment]
歌曲没有放完就播放下一曲，有这样的情况吗？

**Comment by anhoder** [comment]
重新播放这个歌可以复现吗，是不是暂停了一段时间重新播放出现的

**Comment by anhoder** [comment]
Duplicate of #11
