### ISSUE TITLE
播放歌曲报错

### ISSUE THREAD

**Issue by amalaccs** [anhoder/go-musicfox#51]
2023/01/23 23:44:59 catch panic, err: winmm error at waveOutOpen: MMSYSERR_BADDEVICEID
failed to initialize speaker
github.com/faiface/beep/speaker.Init
	/go/src/go-musicfox/vendor/github.com/faiface/beep/speaker/speaker.go:42
go-musicfox/pkg/player.(*beepPlayer).listen
	/go/src/go-musicfox/pkg/player/beep_player.go:183
go-musicfox/pkg/player.NewBeepPlayer.func1
	/go/src/go-musicfox/pkg/player/beep_player.go:67
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571, stack: goroutine 6 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
go-musicfox/utils.Recover(0x0)
	/go/src/go-musicfox/utils/recover.go:8 +0x4f
panic({0x1564e00, 0xc000432768})
	/usr/local/go/src/runtime/panic.go:838 +0x207
go-musicfox/pkg/player.(*beepPlayer).listen(0xc000131e60)
	/go/src/go-musicfox/pkg/player/beep_player.go:184 +0xbb0
go-musicfox/pkg/player.NewBeepPlayer.func1()
	/go/src/go-musicfox/pkg/player/beep_player.go:67 +0x3f
created by go-musicfox/pkg/player.NewBeepPlayer
	/go/src/go-musicfox/pkg/player/beep_player.go:65 +0x216

**Comment by anhoder** [comment]
什么系统

**Comment by amalaccs** [comment]
版本	Windows 11 专业工作站版
版本	22H2
安装日期	‎2022/‎11/‎1
操作系统版本	22621.1105
体验	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by amalaccs** [comment]
> 什么系统

版本	Windows 11 专业工作站版
版本	22H2
安装日期	‎2022/‎11/‎1
操作系统版本	22621.1105
体验	Windows Feature Experience Pack 1000.22638.1000.0
